technology_groups = {
    "javascript": ["javascript", "js"],
    "python": ["python"],
    "java": ["java"],
    "c#": ["c#", "c-sharp"],
    "php": ["php"],
    "oop": ["oop"],
    "typescript": ["typescript", "ts"],
    "ruby": ["ruby"],
    "swift": ["swift"],
    "kotlin": ["kotlin"],
    "sql": ["sql", "mysql", "sqlite", "mssql"],
    "postgresql": ["postgresql"],
    "html": ["html", "html5"],
    "css": ["css", "css3"],
    "sass": ["sass", "scss"],
    "react": ["react", "react.js", "reactjs"],
    "angular": ["angular", "angular.js", "angularjs"],
    "vue": ["vue", "vue.js", "vuejs"],
    "flask": ["flask"],
    "django": ["django"],
    "spring": ["spring", "springboot", "spring-boot"],
    "laravel": ["laravel"],
    "node.js": ["node.js", "node", "nodejs"],
    "express": ["express", "express.js"],
    "tensorflow": ["tensorflow"],
    "pytorch": ["pytorch", "torch"],
    "docker": ["docker"],
    "kubernetes": ["kubernetes", "k8s"],
    "git": ["git", "github", "gitlab"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure"],
    "gcp": ["gcp", "google cloud", "google cloud platform"],
    "hadoop": ["hadoop"],
    "spark": ["spark", "apache spark"],
    "tableau": ["tableau"],
    "powerbi": ["powerbi", "power bi"],
    "hive": ["hive"],
    "mongodb": ["mongodb", "mongo"],
    "redis": ["redis"],
    "elasticsearch": ["elasticsearch"],
    "bootstrap": ["bootstrap"],
    "jquery": ["jquery"],
    "webpack": ["webpack"],
    "babel": ["babel"],
    "graphql": ["graphql"],
    "apollo": ["apollo", "apollo graphql"],
    "selenium": ["selenium"],
    "jira": ["jira"],
    "ci/cd": ["ci/cd", "cicd", "continuous integration", "continuous delivery"],
    "terraform": ["terraform"],
    "ansible": ["ansible"],
    "linux": ["linux", "ubuntu", "debian", "centos"],
    "bash": ["bash", "shell scripting"],
    "matlab": ["matlab"],
    "rest": ["rest"],
    "api": ["api"],
    "artificial intelligence": ["artificial intelligence", "ai"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning", "dl"],
    "natural language processing": ["natural language processing", "nlp"],
    "computer vision": ["computer vision", "cv"],
    "image processing": ["image processing", "ip"],
    "data analysis": ["data analysis", "da"],
    "data visualization": ["data visualization", "dv"],
    "data mining": ["data mining", "dm"],
    "data science": ["data science", "ds"],
    "data engineering": ["data engineering", "de"],
    "data transformation": ["data transformation", "dt"],
    "data integration": ["data integration", "di"],
    "data quality": ["data quality", "dq"],
    "data cleaning": ["data cleaning", "dc"],
    "data normalization": ["data normalization", "dn"],
    "nosql": ["nosql"],
    "fullstack": ["fullstack"],
    "microservices": ["microservices"],
    "drf": ["drf"],
    "fastapi": ["fastapi"],
    "asyncio": ["asyncio"],
}
